---
title: "Efficiency Test"
output:
  html_document:
    df_print: paged
  pdf_document: default
  html_notebook: default
---

# Data

```{r}
y = c(16.08, 33.83, 65.80, 97.20, 191.55, 326.20, 386.87, 520.53, 
      590.03, 651.92, 724.93, 699.56, 689.96, 637.56, 717.41)
t = 1:15
N = 15

inits = list(chain1 = list(theta1 = 702, phi2 = 4.4, phi3 = 0, gamma0 = 1.3, gamma1 = 0.5),
             chain2 = list(theta1 = 10, phi2 = 1.1, phi3 = 2, gamma0 = 0.5, gamma1 = 0.25))
```

# Model

```{r}
cat("model {
  for(i in 1 : N) {
    y[i] ~ dnorm(mu[i], tau[i])
    y.pred[i] ~ dnorm(mu[i], tau[i])

    mu[i] <- theta1 / (1 + theta2 * pow(theta3, t[i]))
    tau[i] <- 1 / (sigma[i] * sigma[i])
    sigma[i] <- gamma0 + gamma1 * t[i]

    res[i] <- (y[i] - mu[i]) / sigma[i]
  }
  theta1 ~ dunif(0, 1000)

  log(theta2) <- phi2
  phi2 ~ dnorm(0, 0.01)

  logit(theta3) <- phi3
  phi3 ~ dnorm(0, 0.01)

  gamma0 ~ dnorm(0, 0.25)
  gamma1 ~ dnorm(0, 0.25)
}")
```

# Test efficiency

## OpenBUGS

```{r}
library(R2OpenBUGS)

par = c("mu", "sigma", "y.pred", "res", "gamma0", "gamma1", "theta1", "theta2", "theta3")

test.bugs = function() {
   result = bugs(data = list("N", "y", "t"),
                 inits = inits,
                 parameters.to.save = par,
                 model.file = "hard_model.txt",
                 n.chains = 2,
                 n.iter = 20000,
                 n.thin = 1,
                 n.burnin = 0,
                 DIC = TRUE)
}

# test.bugs()
```

## JAGS

```{r}
library(R2jags)

par = c("mu", "sigma", "y.pred", "res", "gamma0", "gamma1", "theta1", "theta2", "theta3")

test.jags = function() {
   result = jags(data = list("N", "y", "t"),
                 inits = inits,
                 parameters.to.save = par,
                 model.file = "hard_model.txt",
                 n.chains = 2,
                 n.iter = 20000,
                 n.thin = 1,
                 n.burnin = 0,
                 DIC = TRUE)
}

# test.jags()
```

## Nimble setup

```{r}
library(nimble, warn.conflicts = FALSE)

monitors = list("mu", "sigma", "y.pred", "res", "gamma0", "gamma1", "theta1", "theta2", "theta3")
constants = list(N = N)
data = list(t = t, y = y)
```


## Nimble (standard mcmc)

```{r}
test.nimble.standard.mcmc = function() {
   # model configuration
   code = nimbleCode({
      for(i in 1 : N) {
         y[i] ~ dnorm(mu[i], tau[i])
         y.pred[i] ~ dnorm(mu[i], tau[i])
         
         mu[i] <- theta1 / (1 + theta2 * pow(theta3, t[i]))
         tau[i] <- 1 / (sigma[i] * sigma[i])
         sigma[i] <- exp(gamma0 + gamma1 * t[i]) 
         
         res[i] <- (y[i] - mu[i]) * pow(tau[i], 0.5)
      }
      theta1 ~ dunif(0, 1000)
      
      log(theta2) <- phi2
      phi2 ~ dnorm(0, 0.01)
      
      logit(theta3) <- phi3
      phi3 ~ dnorm(0, 0.01)
      
      gamma0 ~ dnorm(0, 0.25)
      gamma1 ~ dnorm(0, 0.25)
   })
   
   results = nimbleMCMC(code = code,
                        constants = constants,
                        data = data,
                        inits = inits,
                        nburnin = 0,
                        niter = 20000,
                        nchains = 2,
                        summary = TRUE,
                        WAIC = TRUE,
                        monitors = monitors)
}

# test.nimble.uncompiled()
```

## Nimble (custom mcmc)

```{r}
test.nimble.custom.mcmc = function() {
   code = nimbleCode({
      for(i in 1 : N) {
         y[i] ~ dnorm(mu[i], tau[i])
         y.pred[i] ~ dnorm(mu[i], tau[i])
         
         mu[i] <- theta1 / (1 + theta2 * pow(theta3, t[i]))
         tau[i] <- 1 / (sigma[i] * sigma[i])
         sigma[i] <- exp(gamma0 + gamma1 * t[i]) 
         
         res[i] <- (y[i] - mu[i]) * pow(tau[i], 0.5)
      }
      theta1 ~ dunif(0, 1000)
      
      log(theta2) <- phi2
      phi2 ~ dnorm(0, 0.01)
      
      logit(theta3) <- phi3
      phi3 ~ dnorm(0, 0.01)
      
      gamma0 ~ dnorm(0, 0.25)
      gamma1 ~ dnorm(0, 0.25)
   })
   
   model = nimbleModel(code,
                       constants = constants,
                       data = data,
                       inits = inits$chain1)
   
   # MCMC configuration and building
   mcmc.conf = configureMCMC(model, monitors = monitors, enableWAIC = TRUE)
   mcmc = buildMCMC(mcmc.conf, monitors = monitors)
   
   # compile to C++, and run
   compiled.model = compileNimble(model)
   compiled.mcmc = compileNimble(mcmc, project = model)
   
   # run multiple MCMC chains
   results = runMCMC(compiled.mcmc, 
                     nburnin = 0,
                     inits = inits,
                     niter = 20000,
                     nchains = 2,
                     summary = TRUE,
                     WAIC = TRUE)
   
}

# test.nimble.compiled.mcmc()
```

## Nimble (sample from a compiled model)

```{r}
# model configuration
code = nimbleCode({
   for(i in 1 : N) {
      y[i] ~ dnorm(mu[i], tau[i])
      y.pred[i] ~ dnorm(mu[i], tau[i])
      
      mu[i] <- theta1 / (1 + theta2 * pow(theta3, t[i]))
      tau[i] <- 1 / (sigma[i] * sigma[i])
      sigma[i] <- exp(gamma0 + gamma1 * t[i]) 
      
      res[i] <- (y[i] - mu[i]) * pow(tau[i], 0.5)
   }
   theta1 ~ dunif(0, 1000)
   
   log(theta2) <- phi2
   phi2 ~ dnorm(0, 0.01)
   
   logit(theta3) <- phi3
   phi3 ~ dnorm(0, 0.01)
   
   gamma0 ~ dnorm(0, 0.25)
   gamma1 ~ dnorm(0, 0.25)
})

model = nimbleModel(code,
                       constants = constants,
                       data = data,
                       inits = inits$chain1)
   
# MCMC configuration and building
mcmc.conf = configureMCMC(model, monitors = monitors, enableWAIC = TRUE)
mcmc = buildMCMC(mcmc.conf, monitors = monitors)

# compile to C++, and run
compiled.model = compileNimble(model)
compiled.mcmc = compileNimble(mcmc, project = model)
```

```{r}
test.nimble.only.sampling = function() {
   results = runMCMC(compiled.mcmc, 
                     nburnin = 0,
                     inits = inits,
                     niter = 20000,
                     nchains = 2,
                     summary = TRUE,
                     WAIC = TRUE)
}

# test.nimble.compiled.rerun()
```






# Benchmark

```{r}
library(microbenchmark)

times = microbenchmark("OpenBUGS" = {test.bugs()},
                       "JAGS" = {test.jags()},
                       "Nimble (standard mcmc)" = {test.nimble.standard.mcmc()},
                       "Nimble (custom mcmc)" = {test.nimble.custom.mcmc()},
                       "Nimble (sample from pre compiled model)" = {test.nimble.only.sampling()},
                       times = 5)

print(times)
```
